### ISSUE TITLE
How did you add Vuetify

### ISSUE THREAD

**Issue by EmmyMay** [12vanblart/gridsome-vuetify-starter#7]
Hi. You have no Readme.md that even describes what this is all about. How did you add vuetify please?

**Comment by 12vanblart** [comment]
Hi! This repository already has Vuetify set up and is a starting point for a new Gridsome project using `gridsome create https://github.com/12vanblart/gridsome-vuetify-starter.git`.

I've also enabled this repository as a GitHub Template (which I thought I had done before now 😅) if you would rather use that functionality instead. 

If you need to add Vuetify to an existing project, you can follow the instructions listed [here](https://gridsome.org/docs/assets-css/#vuetify) - which is what I followed to install Vuetify initially. 

If you're receiving an error with installing Vuetify in your own repository, drop a link and I can look at what's going on.

Thanks for letting me know that this is unclear - I'll be updating the readme with more information!

**Comment by EmmyMay** [comment]
It all makes sense now and it did make sense when I looked through your package.json. Sorry If I came off as harsh. I was just really frustrated. Thank you for this, the repo saved me a lot of stress

**Comment by 12vanblart** [comment]
No worries - we've all been there before 😅 I'm glad this helped you! Hopefully, my readme changes will help prevent as much frustration for someone else! 

If you run into other issues, feel free to reach out!
